=== alfi10/Practica-Grupal/videoteca.dtd
<?xml encoding="UTF-8"?>
<!ELEMENT videoteca (nombre,ubicacion,fecha_actualizacion,peliculas)+>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ubicacion (#PCDATA )>
<!ELEMENT fecha_actualizacion (#PCDATA)>
<!ELEMENT peliculas (pelicula)+>

<!ELEMENT pelicula (titulo,sinopsis,genero?,enlace,reparto)+>
<!ATTLIST pelicula agno CDATA #IMPLIED duracion CDATA #IMPLIED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT enlace (#PCDATA)>
<!ELEMENT reparto (actor)+>

<!ELEMENT actor (nombre,enlaceWikipedia)+>
<!ELEMENT enlaceWikipedia (#PCDATA)>

=== alfi10/Practica-Grupal/data.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<!DOCTYPE videoteca SYSTEM "videoteca.dtd">

<videoteca>
    <pelicula agno = "1997" duracion ="121">
        <titulo>Star Wars</titulo>
        <sinopsis>
            a
        </sinopsis>
        <genero>Aventura</genero>
        <enlace>https://www.imdb.com/title/tt0076759/</enlace>
        <reparto>
            <actor>
                <nombre>dddddddddddd</nombre>
            </actor>
            <actor>
                <nombre>dddddddddddd</nombre>
            </actor>
        </reparto>
    </pelicula>
    <pelicula agno = "1997" duracion ="121">
        <titulo>Star Wars</titulo>
        <sinopsis>
            a
        </sinopsis>
        <genero>Terror</genero>
        <enlace>https://www.imdb.com/title/tt0076759/</enlace>
        <reparto>
            <actor>
                <nombre>dddddddddddd</nombre>
            </actor>
            <actor>
                <nombre>dddddddddddd</nombre>
            </actor>
        </reparto>
    </pelicula>
</videoteca>
